[package]
authors = ["Victor Aremu <me@victorare.mu>"]
edition = "2021"
name    = "electron-macos-window-extensions"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
block2           = "0.6.2"
napi             = "3.0.0"
napi-derive      = "3.0.0"
objc2            = "0.6.3"
objc2-foundation = "0.3.2"

  [dependencies.objc2-app-kit]
  features = ["block2"]
  version  = "0.3.2"

[build-dependencies]
napi-build = "2"

[profile.release]
lto   = true
strip = "symbols"
