/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Emitted when window key window status changes. */
export declare class WindowEvent {
  type: WindowEventType
}

export declare class WindowObserver {
  constructor(windowHandle: Buffer, callback: ((err: Error | null, arg: WindowEvent) => any))
  stop(): void
}

export declare const enum AnimationBehavior {
  Default = 'Default',
  None = 'None',
  DocumentWindow = 'DocumentWindow',
  UtilityWindow = 'UtilityWindow',
  AlertPanel = 'AlertPanel'
}

/** Deactivate application (move focus to another app). */
export declare function deactivateApp(): void

/** Set window as non-activating panel (interactions won't activate the app). */
export declare function nonActivatingPanel(windowHandle: Buffer, config?: NonActivatingPanelConfig | undefined | null): void

/** Configuration for non-activating panel. */
export interface NonActivatingPanelConfig {
  resizable: boolean
}

/** Remove window from screen list. */
export declare function orderOut(windowHandle: Buffer): void

/** Set window animation behavior for ordering on/off screen. */
export declare function setAnimationBehavior(windowHandle: Buffer, behavior: AnimationBehavior): void

/** Display window and make it the key window (receives keyboard events). */
export declare function showAndMakeKey(windowHandle: Buffer): void

/** Window key window status changes. */
export declare const enum WindowEventType {
  /** Window resigned key window status (no longer receives keyboard events). */
  ResignKey = 'ResignKey',
  /** Window became the key window (now receives keyboard events). */
  BecomeKey = 'BecomeKey'
}
